### ISSUE TITLE
Querying Yabai from the Lua API

### ISSUE THREAD

**Issue by shajra** [FelixKratz/SbarLua#5]
Yabai doesn't seem to send an event for when spaces swap or move.  That complicates app icons for spaces getting stale if opting to use `yabai -m space --swap` or `yabai -m space --move`.

Moving is worse, because every space can move places, invalidating everything.  Swapping just messes up only two spaces.

I can call `sketchybar --trigger space_change`, which seems to get the selection pointed to the right space.  But `sketchybar --trigger space_windows_change` doesn't fix the app icons.  It seems that `space_windows_change` is linked strongly to windows actually changing in the SketchyBar codebase. I'm open to changing this so that I can trigger the event externally.  I suppose that would be another ticket on the SketchyBar repo.

However, I can get the list of apps via scripts from Yabai with something like `yabai -m query --windows --space $POS | jq .[].app`.  So the workaround with non-Lua configuration is there.

In Lua, it's just annoying to deal with JSON, because the parsing libraries available seem a bit underdeveloped.   In the meantime, I'm likely to just use `jq` with an `os.execute` call.  But that seems like it's less in the spirit of why this API exists.

But maybe you have an idea on how to solve my problem that's better than anything I've thought of above.  Thanks for your help.

**Comment by FelixKratz** [comment]
I think it is a good idea to manually update all space windows when sending `sketchybar --trigger space_windows_change`. It should be a very minor change in the sketchybar source. Could you open an issue or PR at the sketchybar repo?

You are correct that it is not in the spirit of this API to do many `os.execute` operations. This is not only because it defeats the purpose of using lua in the first place but also can cause problems, because os.execute is *slow*. In this api event handling is not async, which means that the lua callbacks should be quick such that they do not halt the event pipeline for too long. Thus, when needing to interface with the shell it is better to specify a regular `script` property, which sketchybar handles async itself.

For example, I have a brew package count in my lua bar, but the `brew outdated` command is really slow so I update the package count the regular shell way:
```lua
local brew = sbar.add("item", {
  position = "right",
  icon = {
    string = icons.brew,
    color = colors.orange,
  },
  label = "?",
  update_freq = 3600,
  script='sketchybar --set "$NAME" label="$(brew outdated | wc -l | tr -d " ")"',
})
```

All items which can be handled without interfacing with slow shell calls should be handled in lua and yabai can actually be handled very well in lua. I have a yabai module (similar to this sketchybar module, so a compiled .so file) which interfaces with yabais socket directly and then parses the response into a lua table with the same parsing method I use for sketchybar JSON queries, i.e. the `json_to_lua_table` function:
https://github.com/FelixKratz/SbarLua/blob/260de153682ad01e918a894fa9b4ac9eadb41004/src/parsing.c#L78

This way one can simply use yabai as a natural lua module for example, this is the code I am using in my hotkey manager to send a window to the n-th space on the active display:
```lua
local yabai = require("yabai")

function space.window_to_space(number)
  local spaces = yabai.m("query --displays --display").spaces
  yabai.m("window --space " .. spaces[number])
end
```

**Comment by shajra** [comment]
Hi.

I think I have Sketchybar+Yabai+Lua set up pretty well, using the APIs you've made public thus far.  You got me curious now, though, about two things:

1. Your Lua-based hotkey program.  I looked at your dotfiles repo, and I got the impression that you're still using `skhd`.
2. The `yabai` module you talked about above.  I'm calling `yabai` more from `skhd` than `sketchybar`, but calls to `yabai` are in both.  There's something interesting about going all-in on Lua to stitch everything together.  Get rid of as many process calls as possible.

Are these two projects public?  If they are, are they in a shape to be used by others?

Also, you said that `os.execute` is slow, but hotkey and windowing events only come along so frequently.  I wonder if the work above is nice... but also more of an optimization than I could feel the benefit of as an end user.  I tried to do as much as I could in one `jq` call.  `jq` is surprisingly nice as a language, and I wonder if it's been optimized some for as much usage as it has.  That way, `jq` can offset the expense of the `os.execute` call.  That's the approach my setup takes currently.

**Comment by shajra** [comment]
I took a moment to go through my triggers and see if there were any redundancies.  I didn't find any, but I also took a moment to see where things felt slow.  Now, I'm doing enough stuff in callouts and triggers that switching spaces is noticeably sluggish.  It's not functionally a big deal, because switching spaces isn't that common a task.  But the experience overall keeps my interest in this all-Lua idea.  I think you're moving in that direction already.  Just let me know how I can participate, even if just testing things out with another setup.

**Comment by FelixKratz** [comment]
Both of those projects are not public at the moment. Doing the hotkey managing purely in lua with a native module that directly writes/reads to the respective app socket/mach port is by far the biggest performance improvement I have seen. It takes hotkeys from being noticably not-instantanous to absolutely instant. The latency is reduced to sub-frametime levels and thus indeed quasi-instantaneous. This is especially noticable on space changes, where the entire call stack latency is combined: hotkey -> yabai ->sketchybar. There is no delay in that anymore either.

That said, I have been coding this hotkey manager together with a friend as a first Rust learning project, so I think it is not entirely polished, but it is also compatible with linux and support keykombo sequences.

**Comment by shajra** [comment]
All nice.  I'm very interested.  What do you suggest I subscribe to on GitHub to get notifications of these projects, whether to beta test or help contribute to them?  I'm subscribed to this issue, but can subscribe to something else if you have a preference.

**Comment by FelixKratz** [comment]
I think this is also worth a look: http://www.hammerspoon.org/docs/hs.hotkey.html

**Comment by shajra** [comment]
Yeah, that looks like a good fit.  I'd seen this project a while ago, but
forgot it was in Lua.  If that project is robust enough and maintained,
then I think there's no reason to bother writing something custom.  It
seems to have modal keybindings, which is as complicated as I might need
personally.

And maybe the other stuff is useful too.  Need to look further about how
much is FFI and how much is just process calls.

If all the pieces of Hammerspoon are useful, then it seems like the missing
piece will be your Yabai Lua module.  And then I can start gluing a lot of
Lua together into one massive Lua ball.  See how fast it rolls down the
performance hill.

**Comment by shajra** [comment]
Yeah, that looks like a good fit.  I'd seen this project a while ago but forgot it was in Lua.  If that project is robust enough and maintained, there's no reason I have to write something custom.  It has modal keybindings, which is as complicated as I might need personally.

The other stuff in Hammerspoon seems useful, too.  I need to look further at how much FFI is and how much it is just process calls.

If all the pieces of Hammerspoon are helpful, then the missing piece will be your Yabai Lua module.  And then I can start gluing a lot of Lua together into one massive Lua ball. See how fast it rolls down the performance hill.
