### ISSUE TITLE
Script field vs subscribe

### ISSUE THREAD

**Issue by Pix-xiP** [FelixKratz/SbarLua#9]
I couldn't find anything in the docs about this.

When you use the lua api the set both a script and a subscribe, the subscribe seems to overwrite the script feature and set it to ""

```lua

local a = sbar.add("item", "thing", {
    script = "echo 'hi",
})
```
Gives the query output
```json
{
  "script": "echo 'hi'",
  "click_script": "sketchybar --trigger discord",
  "update_freq": 10,
  "update_mask": 0,
  "updates": "when_shown"
}
```

But if you then add:
```lua
a:subscribe("system_woke", function(env) 
    print("system up") 
end)
```

You get the output
```json
{
  "script": "",
  "click_script": "sketchybar --trigger discord",
  "update_freq": 10,
  "update_mask": 8,
  "updates": "when_shown"
}
```

Is this intentional? I feel like I was able to both set a script and subscribe to an event with the bash version.

**Comment by FelixKratz** [comment]
Yeah, this is intentional. When having a `script` property, we execute it on every subscribed event and routinely, providing the `$SENDER` variable to differentiate between those events in the script. As soon as an event is subscribed to in lua, the event should no longer be handled by the `script`. Thats why I set the `script` property to an empty string every time an event is subscribed to in lua here:
https://github.com/FelixKratz/SbarLua/blob/be2ab89e936236d699b8ab89e6c955e1267a3724/src/sketchybar.c#L253-L269

I am open for discussion about this. It would easily be possible to allow both the `script` property *and* the lua function to handle the event (although that would be a bit janky). What would also work is to modify the event handling in sketchybar such that only events not handled in lua are handled by executing the `script`.

**Comment by Pix-xiP** [comment]
To open the discussion then - this is what I'm currently trying to acheive in lua:

```lua
M.discord = sbar.add("item", "discord", {
	update_freq = 10,
	script = "sketchybar --trigger discord",
	position = "right",
        -- ...
})

M.discord_event = sbar.add("event", "discord")

M.discord:subscribe("discord", M.status_label)
```

Where `status_label` does a call out to `lsappinfo` to get the number of notifications from discord and runs:
```lua
M.discord:set({ icon = { color = icon_color }, label = { string = new_label } })
```

So I'm trying to have the item update every 10 seconds to trigger the discord event - however if I subscribe the item to the event, it removes the script that would trigger its update.

If there is a smarter way to achieve this I'm open to ideas to not have to make potentially janky compromises.

**Comment by FelixKratz** [comment]
The event that is called periodically is called `routine`. So you can remove the `script` poperty and the `discord` event and simply subscribe to the `routine` event of the item instead of the `discord` event.

Another special event is the `forced` event, which is emitted on startup or `--update`.

**Comment by Pix-xiP** [comment]
Ahh legend, that routine event works a charm.

You are correct in what I had assumed - given that I can see no other good reason to want to handle both and make the change. And the `routine` event providing a way to have essentially a polling system when event driven stuff cannot be leveraged. I'm happy to close this as a non-issue.

I also think it is probably for the best to keep the two seperate to not lead people into the exact scenario you described where it would be alot easier to put yourself into an infinite loop.
